image:
  file: .gitpod.Dockerfile
tasks:
  - name: Build
    init: cargo build 
github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true
vscode:
  extensions:
    - matklad.rust-analyzer