[package]
name = "cgroups"
version = "0.1.0"
edition = "2018"

[features]
default = ["systemd_cgroups"]
systemd_cgroups = ["systemd"]

[dependencies]
nix = "0.22.0"
procfs = "0.9.1"
log = "0.4"
anyhow = "1.0"
oci_spec = { version = "0.1.0", path = "../oci_spec" }
systemd = { version = "0.8", default-features = false, optional = true }
dbus = "0.9.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
oci_spec = { version = "0.1.0", path = "../oci_spec", features = ["proptests"] }
quickcheck = "1"
